# Generated by Django 5.0.4 on 2024-07-28 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinValueValidator(6, 'ISBN must be at least 6 characters long')]),
        ),
    ]
